import sys
from struct import unpack

import google.protobuf.message_factory as message_factory
from google.protobuf.descriptor import Descriptor, FieldDescriptor
from google.protobuf.message import Message
from pydantic import BaseModel, create_model

from iot_proto.iot.v1 import iot_pb2

from ...iot.settings import settings
from ..logging import logger


class _UnsupportedType:
    """Sentinel class representing unsupported protobuf type."""

    pass


PROTO_TYPES = {
    FieldDescriptor.TYPE_DOUBLE: float,
    FieldDescriptor.TYPE_FLOAT: float,
    FieldDescriptor.TYPE_INT64: int,
    FieldDescriptor.TYPE_UINT64: int,
    FieldDescriptor.TYPE_INT32: int,
    FieldDescriptor.TYPE_FIXED64: int,
    FieldDescriptor.TYPE_FIXED32: int,
    FieldDescriptor.TYPE_BOOL: bool,
    FieldDescriptor.TYPE_STRING: str,
    FieldDescriptor.TYPE_GROUP: _UnsupportedType,
    FieldDescriptor.TYPE_MESSAGE: _UnsupportedType,
    FieldDescriptor.TYPE_BYTES: bytes,
    FieldDescriptor.TYPE_UINT32: int,
    FieldDescriptor.TYPE_ENUM: int,
    FieldDescriptor.TYPE_SFIXED32: int,
    FieldDescriptor.TYPE_SFIXED64: int,
    FieldDescriptor.TYPE_SINT32: int,
    FieldDescriptor.TYPE_SINT64: int,
}
"""Maps protobuf scalar type constants to Python native types for Pydantic model generation.

This mapping is intentionally limited to scalar types only. Complex types like nested
messages (TYPE_MESSAGE), groups (TYPE_GROUP), and repeated fields require special handling
and are not supported by this mapping. Enum fields are mapped to int since protobuf enums
serialize to integer values.

Note: Python's int type is unbounded, so unsigned and fixed-size integer types (UINT32,
UINT64, FIXED32, FIXED64, SFIXED32, SFIXED64) map correctly to int but don't enforce
the protobuf size/signedness constraints at the Python level.
"""


def get_sensor_payload_descriptor(sensor_type: str) -> FieldDescriptor:
    """Returns the protobuf FieldDescriptor for a sensor type. This descriptor
    can be used to create and populate a message where the sensor type
    fulfills a OneOf constraint in an IotSensorReading message.
    """
    # Get the appropriate message id to use from the proto
    # based on the configured sensor_type, where the setting
    # is one of the sensor type names in the proto enum and the
    # associated value is the proto message id to use for the sensor
    # payload
    try:
        sensor_payload_id = iot_pb2.IotSensorType.Value(sensor_type)  # type: ignore
    except ValueError:
        logger.error(f"Unknown Sensor Type provided: {sensor_type}")
        raise

    # Using the payload id from the proto enum, based on the convention that the
    # enum value is the payload's field ID within the sensor_reading, we can get
    # its descriptor and use message_factory to create an instance of its message class
    try:
        sensor_payload_descriptor: FieldDescriptor = (
            iot_pb2.DESCRIPTOR.message_types_by_name[
                "IotSensorReading"
            ].fields_by_number[sensor_payload_id]
        )
    except KeyError:
        logger.error(
            "No Sensor ID configured and no default given. "
            "Set IOT_SENSOR_TYPE environment variable."
        )
        sys.exit(1)
    return sensor_payload_descriptor


def model_from_proto_descriptor(descriptor: Descriptor) -> BaseModel:
    """Given a protobuf message descriptor, produce a simple pydantic model implementation.

    This factory does not attempt to support all protobuf features, like nested messages, repeated fields, etc.,
    and implements only some well-known scalar types.
    """
    # protobuf msg
    fields_dict = {
        field_name: (PROTO_TYPES[field_descriptor.type], field_descriptor.default_value)
        for field_name, field_descriptor in descriptor.fields_by_name.items()
    }

    return create_model(
        descriptor.name,
        **fields_dict,
    )  # type: ignore


def get_sensor_reading_model(
    reading: bytes, reading_struct_format: str, message_model: BaseModel
) -> BaseModel:
    """Returns an IOT Sensor Reading payload as a Pydantic model instance.

    The Pydantic model class is generated by the Descriptor of the protobuf message that defines
    the sensor reading payload, and the provided data format is used to unpack the reading struct.
    """
    # Pydantic guarantees that field order is immutable, and the pydantic model
    # in use is based on a protobuf message which provides the same contract,
    # so we may zip the fields from the model with the values from the reading to
    # use to initialize the model.
    return message_model(
        **dict(
            zip(
                message_model.model_fields,
                unpack(reading_struct_format, reading),
            )
        )
    )  # type: ignore


def proto_message_from_sensor_bytes(
    reading: bytes,
    reading_struct_format: str,
    field_descriptor: FieldDescriptor,
    message_model: BaseModel,
) -> Message:
    """Returns a protobuf message built from the bytes of a sensor reading. Accesses application
    setting and state for runtime values.
    """
    ...
    # Set up a proto message for the sensor. This includes creating the
    # sensor reading message and the sensor payload message.
    # This is not expected to change during the lifetime of the application.
    sensor_reading = iot_pb2.IotSensorReading()  # type: ignore
    sensor_reading.sensor_id = settings.sensor_id.bytes
    sensor_reading.sensor_type = field_descriptor.number

    reading_object = get_sensor_reading_model(
        reading, reading_struct_format, message_model
    )

    # Create and populate a sensor_payload message with the current reading
    sensor_payload = message_factory.GetMessageClass(field_descriptor.message_type)(
        **reading_object.model_dump()
    )

    # Using the getattr method, we can access variable or dynamic field names in the
    # sensor_reading protobuf message, then use the CopyFrom method to apply another
    # message to that field.
    getattr(sensor_reading, field_descriptor.name).CopyFrom(sensor_payload)

    return sensor_reading
