bootstrap.servers=localhost:29092
security.protocol=SSL
ssl.truststore.location=cert/cacert.pem
ssl.truststore.type=PEM
ssl.keystore.location=cert/admin_ssl_keystore_location.pem
ssl.keystore.type=PEM
