---
name: "Update and Review Dependency Graph"

"on":
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v6

      # The UvLock detector component is not feature complete and therefore not
      # suitable for purpose. In its present state, it does not follow dependencies
      # in arbitrary groups, does not consider alternate sources, etc.
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "0.11.x"
          enable-cache: true

      - name: Turn uv.lock into a SBOM
        id: uv-to-requirements
        run: >
          uv export --frozen --format cyclonedx1.5
          --all-groups --all-packages --all-extras
          --no-annotate --no-emit-workspace --no-hashes
          --output-file sbom.json

      - name: Detect and Submit Dependency Graph
        id: detect
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.1
        with:
          filePath: sbom.json
          # detectorsFilter: PipReport
          # detectorArgs: Pip=EnableIfDefaultOff

      - name: Save component-detection output to file
        run: |
          echo "${{ steps.detect.outputs.snapshot }}"
          if [ -f ./output.json ]; then
            cat ./output.json
          fi

      - name: Dependency Review
        uses: actions/dependency-review-action@v5
        with:
          comment-summary-in-pr: always
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 120
